//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.9151
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D365API.Helpers.D365FOBBISaldoClienteServices
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CompanyField, value) != true))
                {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LanguageField, value) != true))
                {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true))
                {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true))
                {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private D365API.Helpers.D365FOBBISaldoClienteServices.InfologEntry[] EntriesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public D365API.Helpers.D365FOBBISaldoClienteServices.InfologEntry[] Entries
        {
            get
            {
                return this.EntriesField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EntriesField, value) != true))
                {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private D365API.Helpers.D365FOBBISaldoClienteServices.InfologType TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.MessageField, value) != true))
                {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public D365API.Helpers.D365FOBBISaldoClienteServices.InfologType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                if ((this.TypeField.Equals(value) != true))
                {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage
        {
            get
            {
                return this.ExceptionMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true))
                {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType
        {
            get
            {
                return this.ExceptionTypeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true))
                {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                if ((this.RequestIdField.Equals(value) != true))
                {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", ConfigurationName="D365API.Helpers.D365FOBBISaldoClienteServices.BBISaldoClienteService")]
    public interface BBISaldoClienteService
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje conexionOK tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/BBISaldoClienteService/con" +
            "exionOK", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/BBISaldoClienteService/con" +
            "exionOKResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(D365API.Helpers.D365FOBBISaldoClienteServices.Fault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/BBISaldoClienteService/Fau" +
            "lt", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        D365API.Helpers.D365FOBBISaldoClienteServices.conexionOKResponse conexionOK(D365API.Helpers.D365FOBBISaldoClienteServices.conexionOK request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje obtenerSaldo tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/BBISaldoClienteService/obt" +
            "enerSaldo", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/BBISaldoClienteService/obt" +
            "enerSaldoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(D365API.Helpers.D365FOBBISaldoClienteServices.Fault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/BBISaldoClienteService/Fau" +
            "lt", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        D365API.Helpers.D365FOBBISaldoClienteServices.obtenerSaldoResponse obtenerSaldo(D365API.Helpers.D365FOBBISaldoClienteServices.obtenerSaldo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="conexionOK", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class conexionOK
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public D365API.Helpers.D365FOBBISaldoClienteServices.CallContext CallContext;
        
        public conexionOK()
        {
        }
        
        public conexionOK(D365API.Helpers.D365FOBBISaldoClienteServices.CallContext CallContext)
        {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="conexionOKResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class conexionOKResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public D365API.Helpers.D365FOBBISaldoClienteServices.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public string result;
        
        public conexionOKResponse()
        {
        }
        
        public conexionOKResponse(D365API.Helpers.D365FOBBISaldoClienteServices.Infolog Infolog, string result)
        {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerSaldo", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class obtenerSaldo
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public D365API.Helpers.D365FOBBISaldoClienteServices.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public string _codCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=1)]
        public string _compania;
        
        public obtenerSaldo()
        {
        }
        
        public obtenerSaldo(D365API.Helpers.D365FOBBISaldoClienteServices.CallContext CallContext, string _codCliente, string _compania)
        {
            this.CallContext = CallContext;
            this._codCliente = _codCliente;
            this._compania = _compania;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerSaldoResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class obtenerSaldoResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public D365API.Helpers.D365FOBBISaldoClienteServices.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public string result;
        
        public obtenerSaldoResponse()
        {
        }
        
        public obtenerSaldoResponse(D365API.Helpers.D365FOBBISaldoClienteServices.Infolog Infolog, string result)
        {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface BBISaldoClienteServiceChannel : D365API.Helpers.D365FOBBISaldoClienteServices.BBISaldoClienteService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class BBISaldoClienteServiceClient : System.ServiceModel.ClientBase<D365API.Helpers.D365FOBBISaldoClienteServices.BBISaldoClienteService>, D365API.Helpers.D365FOBBISaldoClienteServices.BBISaldoClienteService
    {
        
        public BBISaldoClienteServiceClient()
        {
        }
        
        public BBISaldoClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public BBISaldoClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BBISaldoClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public BBISaldoClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        D365API.Helpers.D365FOBBISaldoClienteServices.conexionOKResponse D365API.Helpers.D365FOBBISaldoClienteServices.BBISaldoClienteService.conexionOK(D365API.Helpers.D365FOBBISaldoClienteServices.conexionOK request)
        {
            return base.Channel.conexionOK(request);
        }
        
        public D365API.Helpers.D365FOBBISaldoClienteServices.Infolog conexionOK(D365API.Helpers.D365FOBBISaldoClienteServices.CallContext CallContext, out string result)
        {
            D365API.Helpers.D365FOBBISaldoClienteServices.conexionOK inValue = new D365API.Helpers.D365FOBBISaldoClienteServices.conexionOK();
            inValue.CallContext = CallContext;
            D365API.Helpers.D365FOBBISaldoClienteServices.conexionOKResponse retVal = ((D365API.Helpers.D365FOBBISaldoClienteServices.BBISaldoClienteService)(this)).conexionOK(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        D365API.Helpers.D365FOBBISaldoClienteServices.obtenerSaldoResponse D365API.Helpers.D365FOBBISaldoClienteServices.BBISaldoClienteService.obtenerSaldo(D365API.Helpers.D365FOBBISaldoClienteServices.obtenerSaldo request)
        {
            return base.Channel.obtenerSaldo(request);
        }
        
        public D365API.Helpers.D365FOBBISaldoClienteServices.Infolog obtenerSaldo(D365API.Helpers.D365FOBBISaldoClienteServices.CallContext CallContext, string _codCliente, string _compania, out string result)
        {
            D365API.Helpers.D365FOBBISaldoClienteServices.obtenerSaldo inValue = new D365API.Helpers.D365FOBBISaldoClienteServices.obtenerSaldo();
            inValue.CallContext = CallContext;
            inValue._codCliente = _codCliente;
            inValue._compania = _compania;
            D365API.Helpers.D365FOBBISaldoClienteServices.obtenerSaldoResponse retVal = ((D365API.Helpers.D365FOBBISaldoClienteServices.BBISaldoClienteService)(this)).obtenerSaldo(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
    }
}
